### ISSUE TITLE
[neko] Image only works on bridge network, not custom or host

### ISSUE THREAD

**Issue by d3nd0** [Kippenhof/docker-templates#14]
Trying to run Neko on Unraid 6.10.3 on a custom network br0 with the docker having its own IP.

I need this to occur so my reverse proxy, which is also on the custom network br0, will communicate with neko.

When installed, there are no port assignments visible (see attachment)

![image](https://user-images.githubusercontent.com/1886642/177022131-7f04d44d-6340-45f8-a624-c0001b2db6f8.png)

Port assignments only seem to be occurring when the docker is setup in bridge mode.

Additionally, when the docker restarts, connection errors are received when a user tries to login (either locally or remote without the reverse proxy). These same connection errors are received when the image is freshly installed on the custom network br0 (which makes sense due to no port mappings appearing).

Any ideas?

**Comment by hofq** [comment]
Hey,
to get it working i changed the IP of "NEKO_NAT1TO1" to the IP of the Neko-Container. 

To Access Neko you have to Type http://<NEKO-IP>:8080 , since port allocations seem to work different in custom br0 containers.


If that is working for you i will update my Documentation and the Description for the Parameters in the Template.

**Comment by d3nd0** [comment]
That seems to work well. Works after a few restarts too. Much appreciated!

**Comment by hofq** [comment]
You're Welcome! 

The Documentation has been Added To
[The Template](https://github.com/hofq/docker-templates/commit/29010abfe32dcb5cf3b49de19592d5c94b1f7f27)
and [The Wiki](https://github.com/hofq/docker-templates/wiki/Neko#Custom-IP)
