### ISSUE TITLE
[actual-server] Why not use the official image?

### ISSUE THREAD

**Issue by PartyLich** [Kippenhof/docker-templates#15]
**Describe the Issue**
Just the question in the subject. Is there a reason the template doesn't point to the [image](https://hub.docker.com/r/jlongster/actual-server) that the upstream repo generates?

At present the code seems to be the same. However it does lead to repeated questions in the Actual discord. I suppose we could redirect them all back here. It isn't clear (to me) that these users are even aware they're pulling a fork, which is a bit concerning.

**Comment by hofq** [comment]
The Official image was not available on the release of my Template. 
i can't follow you on how you think it's concerning, since you can see every step of the Build Process [in Github](https://github.com/hofq/actual-server-docker/actions).
I will switch it if i have checked the Official Image & Build, probably in the next days.

**Comment by PartyLich** [comment]
While the build process is visible, my concern is that it is building a [fork](https://github.com/hofq/actual-server-docker) of the actual repo. At present that fork matches upstream, as I noted. The central issue is extending trust to an additional party. The lesser issue is providing support for users who are not running the main repo's code. It is worth noting that, initially, you've been a great help to those users on unraid making use of your template. Thank you for that!

If a vulnerability/CVE/etc is patched upstream but your personal engagements prevent pulling those changes into the fork in a timely manner, anyone relying on the unraid image is exposed. If you wake up tomorrow and decide you have some nefarious intent, you can modify that fork accordingly. It's happened with npm packages (edit to add: or log4j if you're looking for recency and size). It's happened with browser plugins. I have zero reason to think that's likely with you specifically, but there is precedent. 

A downstream user of the unraid CA now has to assign as much trust to you as they have to Actual's maintainer and contributors. If you're not intending any modification, maintaining a fork presents extra work without any benefit. I'm not sure what one would see as advantageous about that, but please share any advantages you see if you're willing to do so.

In terms of supporting a user, I have the option of a) directing them to you, as they arent running main repo or b) comparing your fork *each time* to see that it still reflects upstream before providing any answer. I'm just a random contributor, I have no official connection to Actual, and thus no obligation to provide help at all; but I'd argue the community works a little better when those that can help decide to do so.

**Comment by hofq** [comment]
Hi,
i compared both images and i see no difference. 
Thank you for the Notice that an Official Docker Image is now avalible, i should have looked at the official Project more often.

Since Persistent Data was not stored in a separate folder before, i will change the image in a week to prevent data loss

**Comment by hofq** [comment]
And, if you have any Unraid-Related Issues, just ping me on Discord in the Conversation. I am Happy to help!

`Johannes Walther#4343`

**Comment by hofq** [comment]
Merged!

**Comment by hofq** [comment]
https://github.com/hofq/docker-templates/pull/16

**Comment by PartyLich** [comment]
Thank you!

⁣--
