### ISSUE TITLE
NEKO_NAT1TO1 should be optional

### ISSUE THREAD

**Issue by m1k1o** [Kippenhof/docker-templates#19]
If `NEKO_NAT1TO1` is empty, it automatically fetches IP address from http://checkip.amazonaws.com (good for people with dynamic IP address). Therefore it should not be required variable.

Also, it should be clear for people, that if they want to have it accessible from outside, they need to put their public IP address there. Maybe like:

> Enter the IP of your Unraid-Server (public/private or your defined IP in Custom: br0 mode)

Btw, thanks for adding neko!

**Comment by hofq** [comment]
I corrected the Description and set it to optional. Let me know if you find anything else.

Thanks for the Correction :)
