### ISSUE TITLE
[actual-server] now requires https

### ISSUE THREAD

**Issue by Codex-** [Kippenhof/docker-templates#20]
The current unraid template links to `http` but actual recently updated to require https: https://github.com/actualbudget/actual/issues/637

When attempting to simply use HTTPS, the container does not appear to be configured for it with this template 🤔

**Comment by hofq** [comment]
Hm, can be tricky. for some reason it does not come with a self-signed certificate out of the box like all other apps that use https instead of http

**Comment by hofq** [comment]
i could build it with an automatic cert generation, but last time i forked their repo they where [not happy about it](https://github.com/hofq/docker-templates/issues/15).
If they haven't come up with a solution in a week, i will try fixing it myself, but sadly i don't have really time for that

**Comment by Codex-** [comment]
Hmmm, I see what you mean, @PartyLich thoughts?

**Comment by PartyLich** [comment]
> Hmmm, I see what you mean, @PartyLich thoughts?

Plenty, but the most relevant to this thread would be
- I'm no longer involved with Actual. The BDFL would be a better person to consult, I assume.
- During the time I was involved, a one week timeline for forward progress on an issue was basically a non-starter. If that's your deadline, I suggest you take the action that solves your problem and worry about upstream later, if at all.

**Comment by hofq** [comment]
For now i recommend you @Codex- to create a config manually and enabling https https://actualbudget.github.io/docs/Installing/Configuration/

**Comment by hofq** [comment]
Fixed by Actual Team: https://github.com/actualbudget/actual/pull/645
