### ISSUE TITLE
[actual] New file takes Data from first file

### ISSUE THREAD

**Issue by Lennert159** [Kippenhof/docker-templates#21]
Hello,

For the moment I have a finance for my own expenses, but I want one with my girlfriend.

But when I make the file, it copies all the accounts and expenses from my own finance.
How can I avoid this?

I run ActualServer on own Dockter-container on UnRaid.

Thanks in advance
Lennert Claeys

**Comment by hofq** [comment]
Hi Lennert,

for me it is working by deleting the cookies and opening the URL, from there i have the button to make a new financial plan:
![grafik](https://user-images.githubusercontent.com/54744977/224512435-17f34efd-fe52-434a-8e73-e87cc11d8185.png)

If i open it, i get greeted by an empty plan:
![grafik](https://user-images.githubusercontent.com/54744977/224512475-d3c1aa7d-7ba9-440e-a6fc-4609da0c9cc3.png)

Have you done it in another way or have i misunderstood your issue?

**Comment by Lennert159** [comment]
Hello,

I deleted the cookies + browser history, but still have the same problem.

I normally use the "Lennert" file, when I added the "gezamelijk" file, I didn't got the message you have. Also when I go back to it, it copies my "Lennert" transactions.
Could it be because I use Google Chrome?

Thanks in advance
Lennert CLaeys
________________________________
Van: hofq ***@***.***>
Verzonden: zaterdag 11 maart 2023 22:35
Aan: hofq/docker-templates ***@***.***>
CC: Lennert159 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [hofq/docker-templates] New file (Issue #21)


Hi Lennert,

for me it is working by deleting the cookies and opening the URL, from there i have the button to make a new financial plan:
[grafik]<https://user-images.githubusercontent.com/54744977/224512435-17f34efd-fe52-434a-8e73-e87cc11d8185.png>

If i open it, i get greeted by an empty plan:
[grafik]<https://user-images.githubusercontent.com/54744977/224512475-d3c1aa7d-7ba9-440e-a6fc-4609da0c9cc3.png>

Have you done it in another way or have i misunderstood your issue?

**Comment by hofq** [comment]
Normally not. Maybe take some screenshots and report your issue to [actualbudget/actual](https://github.com/actualbudget/actual) as i am only Maintaining the Actual App in the Unraid store and they are developing the application and have more experience in troubleshooting and bug fixing.

You can mention this issue with the link,  so they can see what you have already tried.

I'm sorry that i couldn't help
