### ISSUE TITLE
[actual-server] official image switch

### ISSUE THREAD

**Issue by goldbattle** [Kippenhof/docker-templates#26]
The official images seem to now be `actualbudget/actual-server` and the data path should just be a single path `/data` in the container according to their guide.
https://actualbudget.org/docs/install/docker#launch-container-using-docker-command

These settings seem to work well for me:
![image](https://github.com/hofq/docker-templates/assets/2222562/93dba90e-ae9d-403b-a30b-32860873bf28)

**Comment by hofq** [comment]
Hi, sorry for my late change.
I already saw the pull request but i've wanted to review the new image first.
Edit: Reviewed it Now, PR is merged

**Comment by hofq** [comment]
#25
