### ISSUE TITLE
Actual Budget Updates?

### ISSUE THREAD

**Issue by SageDest** [Kippenhof/docker-templates#27]
Is there something needed to get the docker to update to the newest version? From what I can see Actual is now on version 24.5 and the docker is stuck to version 16.15.1 which is 2+ years old. Thanks for your help.

**Comment by hofq** [comment]
Hm, maybe you are still on the old image. Please check the current used image and update the app itself through the community store to get a newer version.

Before doing that, please check if the data directory is mounted correctly. For that you have to look inside the container and check if the path that contains data is also mounted to your host

**Comment by SageDest** [comment]
Okay, looks like it was a good combination of all of those. I was stuck on an old container, and changed that to the new one. Then fiddled with it to get the HTTPS working, which needed the whole data mount point. Thanks for your help.

**Comment by hofq** [comment]
Thank you for the update. Please let me know if there is anything not working or outdated with the current Acutal App in Unraid so i can have a look
